export const nhlTeams = [
  "New Jersey Devils",
  "New York Islanders",
  "New York Rangers",
  "Philadelphia Flyers",
  "Pittsburgh Penguins",
  "Boston Bruins",
  "Buffalo Sabres",
  "Montreal Canadiens",
  "Ottawa Senators",
  "Toronto Maple Leafs",
  "Atlanta Thrashers",
  "Carolina Hurricanes",
  "Florida Panthers",
  "Tampa Bay Lightning",
  "Washington Capitals",
  "Chicago Blackhawks",
  "Detroit Red Wings",
  "Nashville Predators",
  "St. Louis Blues",
  "Calgary Flames",
  "Colorado Avalanche",
  "Edmonton Oilers",
  "Vancouver Canucks",
  "Anaheim Ducks",
  "Dallas Stars",
  "Los Angeles Kings",
  "Arizona Coyotes",
  "San Jose Sharks",
  "Columbus Blue Jackets",
  "Minnesota Wild",
];

export const years = [
  "Current Season",
  "2015-2016",
  "2016-2017",
  "2017-2018",
  "2018-2019",
  "2019-2020",
  "2020-2021",
  "2021-2022",
  "2022-2023",
]